<!-- <label for="cuisine">Choose from dropdown</label> -->
<select name="cuisine" id="cuisineList">
    <option value=""></option>
    <option value="African" [@African]>African</option>
    <option value="American" [@American]>American</option>
    <option value="British" [@British]>British</option>
    <option value="Cajun" [@Cajun]>Cajun</option>
    <option value="Caribbean" [@Caribbean]>Caribbean</option>
    <option value="Chinese" [@Chinese]>Chinese</option>
    <option value="Eastern European" [@Eastern European]>Eastern European</option>
    <option value="European" [@European]>European</option>
    <option value="French" [@French]>French</option>
    <option value="German" [@German]>German</option>
    <option value="Greek" [@Greek]>Greek</option>
    <option value="Indian" [@Indian]>Indian</option>
    <option value="Irish" [@Irish]>Irish</option>
    <option value="Italian" [@Italian]>Italian</option>
    <option value="Japanese" [@Japanese]>Japanese</option>
    <option value="Jewish" [@Jewish]>Jewish</option>
    <option value="Korean" [@Korean]>Korean</option>
    <option value="Latin American" [@Latin American]>Latin American</option>
    <option value="Mediterranean" [@Mediterranean]>Mediterranean</option>
    <option value="Mexican" [@Mexican]>Mexican</option>
    <option value="Middle Eastern" [@Middle Eastern]>Middle Eastern</option>
    <option value="Nordic" [@Nordic]>Nordic</option>
    <option value="Southern" [@Southern]>Southern</option>
    <option value="Spanish" [@Spanish]>Spanish</option>
    <option value="Thai" [@Thai]>Thai</option>
    <option value="Vietnamese" [@Vietnamese]>Vietnamese</option>
</select>
